os: linux
arch: arm64-graviton2

sudo: required
services:
  - docker
addons:
  apt:
    update: true

env:
  global:
    - secure: 4kzg9UJoZeUY6RT4X4iPRbn+zfs6+ulfP0y49yK77XVvuq2lJ2gDXCkXiLUp3K7Yo5ym9a1SpdlswsAJyICLFETolNt7QfUe6Ap11zxoizAZ6JxIKa+bw9rjAIonKHrwGql+lIWwgwlVfRoeEUb26wY5zBhdWqCpH/o4zHk34H1oCKCGB6mTPvcr3C6+7ydFsa56QCN11P+kv1sxzSB1TNgvBdzdHKYlqvgjVMnKRUZMAxaIdt8iYznY9cwYcD8mzhUiuMV09e/yyLcLDEKL0d/WS9ifm3avwdOvXMksb6dqx9NJznYWkdThDb2LCpepgFm0lt44RW7WhBxpRye84ozpN5Y+HcA66zrtyl4jqbLwNu1RoRU86h+IYfX8kiuW1aW4iND43RNRdEV7tH69sOASKRzUpufLiVWgCGW+fKp0euaQrJ6YaJtOVj5u7yq3d/5qm6Ly8VvcyT9x/xFdMuo3gEpsHhZVgJ3xALGg8D2ROgSoWwy+nT0hKLyDtBsDkHooklfWWbA7pxSro0SumoDS/6G4UTj4KOJET4pCnv/TdvnXtQI/k9oUAc8bXGydmzBPHbFhIjzzIRPwQVbOf6yxSX4NmoH0hzXdImijNOE7lqXrTFj7KLSjPL68QhvQTv0u6+TyRP1auHF4La2xypHYmS4uRZm3iGL5hlPnxU0=
    - secure: xmtztoTl4GQitg3W0fgnRFkwwcim6EZrfbp+p3bBLKjl7Wc46qFtzzYqM3gQ+28DVqz/+tDof/PSbxhpSoZlzK1TBviuXYRULTHvj2aYvhzXVXDZscQgbQRKIvpF1OZsoQ/r2CvV7u6EgvoIq+G8NTjRLOxxed1vU0/bWlZUfC3e9fmvVGSVw1O/1Uh2O6P5jM3kyuxYST8pKHr0Ix//Z4gGAWKOdylHB2KBIgF5cThA4paFY6SK/tVh52LLMaUNyFT23sCYb8ReGqs/F+fJc5C/2REP1fXfTNukL8rkFO3TH++NlQmTqhD9qsHXlSY1jvBnwWwi6LJHQH818kVvw6K7VWVXUe6wg4uz5vO1d9IeBo/7yelTVMIaAHGCfspst0LDKyuZy3yIticba1N8AOygyk70RQyvlBtfHyp+k2BTP0zZxx1W/v5mzGks7t+MT4XObwnmeKbOr5wMH6Yz1fSAiEwMCqZkA/ezyJU37Iw8RXKIdYITa63fJ6A4Tv3Bxzy5undS8XroHalAejGq/UsLiLF04cTeMPenlt70jGX0PEsDgz8r1paoojYxzo/HKCWl3pRlUBxpbHXU7LZnZHepbcgSZQPpra0F1w++7qN8C6BIIItSAB+P0PqzvCWx02e96xKiECDVSA186q9ervXQvwExxwuWVb2dX0h/BqI=

before_install:
  - sudo apt-get -y install pwgen #used in Makefile to generate the random admin password

before_script:
  - make pull-base

script:
  - make build

after_success:
  - make jocker
  - "./scripts/jenkins-wait.sh Jenkins/job/Setup"
  - make test || travis_terminate 1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    make release; fi
