sudo: required

env:
  - IMAGE_NAME="jocker"

services:
- docker

script:
- make build

after_success:
- make jocker
- make test || travis_terminate 1
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

