---
credentials:
  system:
    domainCredentials:
      - credentials:
          #######
          # User Auth
          #######
          - usernamePassword:
              scope: "GLOBAL"
              id: "github-ci-user-basic-auth"
              description: "Github CI User Basic Auth"
              username: "admin"
              password: "admin"
          ########
          # Tokens
          ########
          - string:
              scope: "GLOBAL"
              id: "github-ci-user-token"
              description: "Github CI User Token"
              secret: "token"
