---
jenkins:
  nodes:
    ########
    # Deploy
    ########
    - permanent:
        name: "docker-1"
        labelString: "docker"
        nodeName: "docker-1"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false
