---
credentials:
  system:
    domainCredentials:
      - credentials:
          #######
          # User Auth
          #######
          - usernamePassword:
              scope: "GLOBAL"
              id: "github-ci-user-basic-auth"
              description: "Github CI User Basic Auth"
              username: "admin"
              password: "admin"
          ########
          # Tokens
          ########
          - string:
              scope: "GLOBAL"
              id: "github-ci-user-token"
              description: "Github CI User Token"
              secret: "token"
          ########
          # Deploy Keys
          ########
          - basicSSHUserPrivateKey:
              scope: "GLOBAL"
              id: "deploy-key-shared-library"
              username: "root"
              passphrase: ""
              description: "Deploy key for global shared library"
              privateKeySource:
                directEntry:
                  privateKey: ! '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAutBHh1pD4y1E+HG03opH2uA8wiUgP5naW0OkFMP7ijRhIpXvfeRY
JoZvd9XpP5VZwEOm3uq3KiR61Iqu08ljsDf6H4xZc6DUXl6DK72jf6sJpnSjHIg1OFdmak
CLccctSbnEfS4qekQ2Iqvhp36/E4kvIGOKr/cErajJwuRNbPbA4ZvH+dVjQTVdm1OvOXH5
mBvZQsELpHBArrVIhqm0k2HzAAGuuilO68Wo7PZ+F4XWIJv6zVCZ5sYEQAgWAwHYFat5RD
6sOLq1oJSMs9JQShJ+ovRfz5xJt3YZq0Vo6omV01eqaEMkcy3E/eYqADIwyheeCuQq1a3w
lTO7263REob4A2AZT92saZRwaolppdc0bnQ5CmRzH5Xjp/ATEJgJuMKXyQJVUKVZqKLkoi
kOBWywayobHQDihJgR7or74DScmCQ+9RgSg9ySIvtzOtcDdz5HTGNw7Uuy33HVVuyr2ayf
6R1w9jxZMiD5jnhpKhupn+gktY19FwkGFvT7v9xCI7YYrFdXtPmyZdA0J3Y4WuwcJh+dGR
QWS5PGwlqCgLY5ZkGIRPUdOUcENeWR2KR3uIMOjoeAbJVzeZ2eUYkS7pXJZEOWKiGkLhxO
5jwQqEqtcVLsE9aw2hxgRBp5Iib+SY7ZEqVKJRHFMfYYIVY4m8266fQU4X8dkTcKuPF6V0
MAAAdQERZ/zBEWf8wAAAAHc3NoLXJzYQAAAgEAutBHh1pD4y1E+HG03opH2uA8wiUgP5na
W0OkFMP7ijRhIpXvfeRYJoZvd9XpP5VZwEOm3uq3KiR61Iqu08ljsDf6H4xZc6DUXl6DK7
2jf6sJpnSjHIg1OFdmakCLccctSbnEfS4qekQ2Iqvhp36/E4kvIGOKr/cErajJwuRNbPbA
4ZvH+dVjQTVdm1OvOXH5mBvZQsELpHBArrVIhqm0k2HzAAGuuilO68Wo7PZ+F4XWIJv6zV
CZ5sYEQAgWAwHYFat5RD6sOLq1oJSMs9JQShJ+ovRfz5xJt3YZq0Vo6omV01eqaEMkcy3E
/eYqADIwyheeCuQq1a3wlTO7263REob4A2AZT92saZRwaolppdc0bnQ5CmRzH5Xjp/ATEJ
gJuMKXyQJVUKVZqKLkoikOBWywayobHQDihJgR7or74DScmCQ+9RgSg9ySIvtzOtcDdz5H
TGNw7Uuy33HVVuyr2ayf6R1w9jxZMiD5jnhpKhupn+gktY19FwkGFvT7v9xCI7YYrFdXtP
myZdA0J3Y4WuwcJh+dGRQWS5PGwlqCgLY5ZkGIRPUdOUcENeWR2KR3uIMOjoeAbJVzeZ2e
UYkS7pXJZEOWKiGkLhxO5jwQqEqtcVLsE9aw2hxgRBp5Iib+SY7ZEqVKJRHFMfYYIVY4m8
266fQU4X8dkTcKuPF6V0MAAAADAQABAAACAGj+IAVZXOg0DBxZw56DNykzd9JhjUNRk+BR
Hsmw8BFXqPQIMoadrFFSoxlFtwbOSJf/La0BW5oq0IHdw64x9H4Yp9HNToTm8hRrp+sQdP
COzyinSvkBMHAO5vd2eSikGbbi2iTEqoj3BznrQjKh0IAJTNw2Nb755L45K9QF/eHsuLDT
ncuy+0qt1IM0wDlX7kBn/m4/Eu0DTccjCbTtchiXJzxstafZCYsHFw6+5lUQGi1PnOCBmU
2TItZd9QkRo0FikxAg7Sgg/21Vr9JstEU9KcEp+SM0olWi4YBZzUJruzIBhjt86OJ26c0M
67QagUNDjMZwQAbB8IHaho1LnkGFhQCEmo4qb2GhIa0IM22PlvNa4orp6Cppv7STNyC8GU
ZOQFEi8zFA0AZ3MH3tpYA3vM8TfjNHVB8CfPwh873zOyHRgWgiAPVtFbdiNWe2+gy4Zn2M
BelZFQvEkXTx2l546dSJMhdKIcYWTpGSffn/oQ4+qZCEXHyj9hST4rvUKQ7Z09iRX2hSKX
/ECT17iZNyF6bqjWQ9uxDE8aAQPbT7aYyGVi1g1pgK+I4Sldj1/t+ktom3DZxB0LNbrqNz
kMxSlRdna6mAYW5/89MG2INzffDM4MetKK7+lR2TQzOQYCtFhQA7MXwP+uh1qzMqCN85UN
nskdj+AZGJIVwHrMJpAAABABXTz5wK24Sku8GOG0FnAJ2pQien0+Z5yplbkuqYUq0tOdFs
cwzwvObop0sfldyExhHRpYSvXewg2GKhsMApH0651IY+UHD/r2Iz4mpHz5nmuPozc5+kBK
DP0ZQXVJhGGZ7rf6CegaCIJgMOai8NscB8fE6BfgL9eiXslhvMR4uLCoZqrtjyqeLkCTKV
8fty6w6gWQkfuTDYrBHJ2fxBEKpwnxHhMGYMG/sATrrGiXThh8n51as3/ynRTHzNk3Ab9M
y/X7FPlDaaidQdsxJD5kqMlXSSKyiZ9M3FVvHCBpOvQcJ8CZf7Js0aVLvRmxpfWZhR4h/6
zPQi6eXT/T43evMAAAEBAPA29KHi61sT1sg48Kqmgdl7LTuf9tHcVnleOQZEqq2p/9A3pk
ugOX3qgF05z2LsfnWlbVk9I1vrdY295t7hgDSu0AzQndmTHE4qgQ92tntDy0Y9OLkDkzN2
hiWb503n6jp/9oYYxnGyRk8zXyKWXyBRlKFdK/r99UWFjdewcqCA0tDxQBfVnpjFR/yjdV
/+81UBl0AD9KPNxS7noizJoW22inlGOn63aFSSJ7tqNeDUhRHjl//HX7GAUyHCyevBVPT1
2ql98leXdGIye9+lLDVg8Lr+eDWxd0z+OwiWxjVRnj+1io1hz6nBeZ7Nmq+1gndAjw5Ybh
2qIWup+J4YgO8AAAEBAMcW+g/LYXAshhbKiwRzUztq9cw1eu8nBAlbw5bXu5G+Z0b4Wedy
jc1pgTo2p8dLroDon6MqwbDePm4dE6CRANKZNcwjEJIb6HvcRqTqCWe2OLH6nqdvcsZy7j
QT1p1GnMbv4+QiRRmCc5QwpnhAVwajRJVlPsKF6I2AErkzbCfvBykKIa8RQjB0x5q4ALzi
gyL076XYm1txt0LuOocwGI2EU1IyCxS5ulV2TwDApIKDsqKeLMs+HlGcnG88X8fvqhOw3N
P9c/GXImcS2h30MBh8ffXn6zI8PBTLcwnNdfnO5RUEwelXtAnIYB3wkAZV4rNFTw0aqjgu
46FLbwHQpu0AAAAYZnJhbmsuaXR0ZXJtYW5uQHlhaG9vLmRlAQID
-----END OPENSSH PRIVATE KEY-----'
